#!/bin/bash
#
# .SYNOPSIS
#
#
# .NOTES
#     Author          : Wilson Siano
#     LinkedIn        : linkedin.com/in/whsianoo/
#     GitHub          : github.com/whsiano
#     Date Created    : 2026-09-23
#     Last Modified   : 2026-09-23
#     Version         : 1.0
#     CVEs            : N/A
#     Plugin IDs      : N/A
#     STIG-ID         : ???
#     Documentation   : ENTER-STIG-ID-WEBSITE
#
# .TESTED ON
#     Date(s) Tested  :
#     Tested By       :
#     Systems Tested  :
#     Bash Ver.       :
#
# .USAGE
#     Put any usage instructions here.
#     Example syntax:
#     $ sudo ./ENTER-STIG-ID.sh
#

